client-id: ${GOOGLE_CLIENT_ID}
client-secret: ${GOOGLE_CLIENT_SECRET}

#github-client-id: ${GITHUB_CLIENT_ID}
#github-client-secret: ${GITHUB_CLIENT_SECRET}



spring:
  application:
      name: ssia-ch16-ex1
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
          google:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}

          my_authorization_server:
            client-id: client
            client-secret: secret
            client-name: Custom
            provider: my_authorization_server
            client-authentication-method: client_secret_basic
            redirect-uri: http://localhost:8080/login/oauth2/code/my_authorization_server
            scope:
              - openid


        provider:
          my_authorization_server:
            issuer-uri: http://127.0.0.1:7070
logging:
  level:
    root: info
